blank_issues_enabled: false
contact_links:
  - name: Questions / Help
    url: https://github.com/neat-pulse-community/community-hub/discussions
    about: Ask questions or discuss ideas in Discussions.
