name: Auto Thank on Membership Request
on:
  issues:
    types: [opened]
jobs:
  thank:
    if: contains(github.event.issue.labels.*.name, 'membership-request')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const body = `Thanks for applying! A maintainer will review your request shortly. \
If approved, you'll receive a GitHub invite to the org.`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body
            });
